### PR TITLE
💄 Don't show incorrect type warning

### PR DESCRIPTION
**Pull request by mrmlnc**

### CODE REVIEW

**Comment by egamma** [comment]
Not allowing `null` was intentional. Then the user gets the warning so that they enter the value as a string. An alternative is to change the default to be the empty string `""`. I will check what is more common in the current settings.

image

**Comment by mrmlnc** [comment]
Can be closed? :)

**Comment by egamma** [comment]
@mrmlnc thanks for the reminder. Let me check again, what the common convention is.

@aeschli @bpasero what is the commonly used as the default value for optional settings of type string? The current default value is `null` should it be the empty string `""`?

**Comment by bpasero** [comment]
Looks like if you do not specify a default in code, it ends up being the empty string:

image

**Comment by aeschli** [comment]
@egamma We never standardised on that.
A count shows 8 settings use null and 5 settings use the empty string. 3 of the 5 are tslint.

**Comment by egamma** [comment]
As @aeschli points out tslint is inconsistent... So changing the default to the empty string as suggested by @mrmlnc originally. Apologies for the detour.

**Pull request closed without merging**
