### PR TITLE
Add jsEnable option

### LINKED ISSUE #149: Extension should provide options to disable TSLint of JS files
With the latest changes TSLint now automatically activates on JS files. If users want to use ESLint for JS file and TSLint for TS files in the same workspace we should allow users to disabled TSLint on JS files.

### PR DESCRIPTION
**Pull request by YuichiNukiyama**
fixes #149

### CODE REVIEW

**Comment by sqren** [comment]
Looking forward to this being merged in.

**Comment by egamma** [comment]
@YuichiNukiyama thanks for the PR. I've published it as part of vscode-tslint 0.8.1. I've changed the default to false, since users where confused that tslint is active by default on .js files.

We should revisit the implementation once the language server protocol 3.0 is out. With this protocol version we can dynamically change the configuration so that .js files are not synchronized to the server, when jsEnabled is false.

**Comment by jacobbogers** [comment]
Any progress on this issue?

**Comment by egamma** [comment]
@jacobbogers what issue do you exactly refer to? The PR is about enabling a jsEnable option and this is in place since a while.

**Pull request merged**
