### PR TITLE
working proposal for autofix based on eslint example

### PR DESCRIPTION
**Pull request by rlasjunies**
Hi @egamma,

 As proposed here is the PR for tslint autofix.

 * it's based on eslint autofix proposal
 * autofix rules are stored in a dedicated file: tslintautofix.ts (7 autofix for now, willing to increase)

Work pretty fine for now.

Let me know your feeling.

BR

### CODE REVIEW

**Comment by egamma** [comment]
@rlasjunies thanks, I took a quick look at the code and it looks promising. I need more time for a deeper look.

I think we would get more quick fixes if the tslintautofix.ts becomes part of tslint, the way you wrote the code it is independent of VS Code.  @unional, @JKillian  what do you think?

**Comment by JKillian** [comment]
Hi all, auto-fixing problems is a feature that we'd like to have in TSLint, although as far as I know, there's been no implementation work on it (outside of this anyways).See https://github.com/palantir/tslint/issues/561, it would probably be best to have a short proposal written up there documenting what sort of API a feature like this would have and basic implementation ideas

**Comment by egamma** [comment]
@JKillian makes sense to start with an API proposal.
Since VS Code integrates several linters it would be desirable when the different linters use a similar API for auto fixing. I therefore suggest to also consider the ESlint as a source for inspiration.

@rlasjunies do you have the cycles for this? we could also involve @dbaeumer given his autofix work for eslint. 

I'll still look into make this PR available in the tslint extension so that we get feedback from users on the auto fix UI support.

**Comment by rlasjunies** [comment]
Hi @egamma, @JKillian,

 I'll will have a look in the TSLint API, digest and hopefully propose something ;-)

This week will be hard ... beginning of May I'll be back to you.

**Comment by egamma** [comment]
@rlasjunies I'll reopen since I still want to look into it and will try to make it available as is so that we get feedback from users. This is independent of whether the autofixes come from tslint or here.

**Comment by egamma** [comment]
The PR looks good, thanks @rlasjunies !

**Comment by ericanderson** [comment]
This was announced in today's update for VSC, but doesn't seem to be shipped?

**Comment by egamma** [comment]
Thanks for the reminder. Published the version as 0.5.25.

**Pull request merged**
