### PR TITLE
autoFIx all + fix indent: several tabs

### LINKED ISSUE #52: TSLint autoFix should support a Fix all command like ESLint does
In ESLint you can F1 > ESLint: ... to fix all autofixable problems. The advantage is that the command can be bound to a keyboard shortcut if necessary

### PR DESCRIPTION
**Pull request by rlasjunies**
@egamma here is the proposal. This should fix #52 and another issue I identified

### CODE REVIEW

**Comment by egamma** [comment]
@rlasjunies thanks, I'll look into this soon. Just a quick question on this auto fix:

>"Replace 1 tab by 4 spaces

The hard coded `4` bothers me. Shouldn't this correspond to the user setting `editor.tabSize`?

**Comment by rlasjunies** [comment]
It bother me too.I did a quick search not finding how to get the value.
I'll be happy to fix.
How can we get the settings value (editor.tabSize)? What is the api?

Another topic,
Is there some changes in the debug, I've difficulties to debug the
extension after a fresh installation. The default value of launch.json does
not seems to work anymore (on my conf).



2016-06-15 10:02 GMT+02:00 Erich Gamma <notifications@github.com>:

> @rlasjunies <https://github.com/rlasjunies> thanks, I'll look into this
> soon. Just a quick question on this auto fix:
>
> "Replace 1 tab by 4 spaces
>
> The hard coded 4 bothers me. Shouldn't this correspond to the user
> setting editor.tabSize?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Microsoft/vscode-tslint/pull/55#issuecomment-226116377>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABX4LxDM7yWTWlAZwNyq-z1ITTtdzsJUks5qL7GwgaJpZM4I0sTC>
> .
>



-- 
Richard Lasjunies

**Comment by rlasjunies** [comment]
I've found the solution, to have debugging working fine.

the content of launch.json must be:

```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch Extension",
			"type": "extensionHost",
			"request": "launch",
			"runtimeExecutable": "${execPath}",
			"args": [
				"--extensionDevelopmentPath=${workspaceRoot}"
			],
			"stopOnEntry": false,
			"sourceMaps": true,
			"outDir": "${workspaceRoot}/../tslint/server",
			"preLaunchTask": "npm"
		}
	]
}
```

Now I have another issue: 

> property `publisher` is mandatory and must be of type `string`

**Comment by rlasjunies** [comment]
I've got thre reason of the second issue. We need to modify the `package.json` file adding 2 properties: `publisher` and `engines.vscode` as followed

```
{
	"name": "tslint-server",
	"version": "0.2.0",
	"publisher": "microsoft	",
	"description": "TSLint Linter Server",
	"engines": {
		"node": "*",
		"vscode":"0.10.x"
	},
	"private": true,
	"dependencies": {
		"minimatch": "^3.0.0",
		"vscode-languageserver": "^2.0.0",
		"semver": "^5.1.0"
	},
	"devDependencies": {
		"typescript": "^1.8.9"
	},
	"scripts": {
		"compile": "installServerIntoExtension ../tslint ./package.json ./src/tsconfig.json && tsc -p ./src",
		"watch": "installServerIntoExtension ../tslint ./package.json ./src/tsconfig.json && tsc --watch -p ./src"
	}
}
```

**Comment by egamma** [comment]
Regarding the hardcoded tabs size. When [configuring the client options](https://github.com/Microsoft/vscode-tslint/blob/master/tslint/extension.ts#L21) you can define which configuration sections should be synched to server. There you can include the editor section as well. However, this still isn't good enough, since the editor computes the tab size based on the contents of the file. There is currently no API to get at this computed tab size.

**Comment by egamma** [comment]
published in 0.5.31

**Pull request merged**
