### PR TITLE
add command and basic tslinthelpers

### PR DESCRIPTION
**Pull request by rlasjunies**
Hi,

 In several cases it's easy to "automatically" solve the tsLint warning. For example, warning about missing whitespace, ' should be ", missing semicolon. 

 In this PR, I propose you:
 * add a new vscode command named: tslint.helper
 * definition of helpers ( the 3 examples above )
 * activate code light bulb if a helper can be run

Let me know if you are interested in, if you may integrated in your repo/extension, in with condition. If not, do you accept that I create my own vscode extension and publish it?

 Thank for your great job.

Sincerely,

### CODE REVIEW

**Comment by egamma** [comment]
@rlasjunies I like this feature a lot. 

In your implementation the fixes are computed on the client, but the diagnostics are found in the server and then sent into some minimally digested form to the client. Have you considered to do this work on the server where we have the full tslint functionality available. My concern is that for some quick fixes you need to be really close to tslint, may be even have access to the AST.

**Comment by rlasjunies** [comment]
Thank for the comment.

I did not considered "server side" as it's my first extension and I do not know a lot there. Let me have a look in and be back to you after.

**Comment by rlasjunies** [comment]
I had a look in the extension server side by I did not found the opportunity.

Did meant tsLint "server"? If yes, I feel there are opportunities but in that is a new concept. I feel that the role of the editor to help while coding. This type of code modification is the concern of server side only in some specific cases in the integration of the product. Not at the coding time.

Do not hesitate to correct me if I missed something.

PS: I found 1 bug in 1 rule and I already added another one (trim trailing spaces)

**Comment by egamma** [comment]
Sorry I meant this document https://code.visualstudio.com/docs/extensions/example-language-server and the section https://code.visualstudio.com/docs/extensions/example-language-server#_additional-language-server-features. As you can see you have all the features that are available on the client on the server. Since the server runs tslint and creates diagnostics it is closer to the action, e.g., it gets the diagnostics from tslint directly. If you do it in the client then you have to re-analyze the diagnostic message you have produced on the server.

We want to revisit quick fixing from linters in particular eslint which already provides quick fixing support and you get the quick fix information from eslint. We should use a consistent approach for quick fixing from linters. 

Having said this, I want hold back on taking this pull request until we have explored the quick fix approach. Since your extension works nicely I suggest to publish it as a separate extension and you get feedback etc.

**Comment by egamma** [comment]
Actually vscode-eslint is now adding light bulps for quickfixes and autofixing on save. Suggest to use the same patterns.

**Comment by rlasjunies** [comment]
Hi Erich,
I've found the communication between @mysticatea and @dbaeumer. 
I've check the code of mysticatea for the server side. I understand better your expectation.

I may work on it next week-end.

My current thought is:
* load the helpers on the server side (there is no autofix in the TSLint engine, as far as I know)
* in doValidate for each problem, add the function autoFixIt in the diagnostic object
* ... I think it should be callable from client action or the autosave (as proposed by vscode-eslint)

Talk to you soon

**Comment by egamma** [comment]
Great, but let's make sure that the latest version of the quick fix support from @dbaeumer is checked in. I haven't seen it yet.

**Comment by egamma** [comment]
@rlasjunies the quickfix support for vscode-eslint was just checked in by @dbaeumer  https://github.com/Microsoft/vscode-eslint/commits/master

**Comment by rlasjunies** [comment]
@egamma just to inform you that I've already merge a good part of the work from vscode-eslint. Hopefully I would propose you a PR after next week-end.

I've one question: do you have recommandation on which version of vscode, vscode-languageserver, vscode-languageclient dependencies we should use. I currently have "strange" behaviors in the communication between the client/server communication (malformed stream messages). 

I've seen that vscode-eslint removed the feature in the last commit do you know the reason.

**Comment by egamma** [comment]
@rlasjunies sorry I missed the last comment (feel free to ping).

I've updated the vscode-tslint dependencies to the VSCode 1.0 and the language service protocol 2.0. The changes for the language service protocol where minor. 

>I've seen that vscode-eslint removed the feature in the last commit do you know the reason.

The quick fix action functionality is now covered by code actions. If we provide a quick fix action then we should avoid that each linter adds its own. 

The auto fix on save needs more support by vscode (a sync aboutToSave event) to implement this properly.

**Comment by egamma** [comment]
Closing in favor of #47

**Pull request closed without merging**
