### PR TITLE
Support javascript files

### LINKED ISSUE #51: How to use TSLint vscode extension to lint *.js file?
How to use TSLint vscode extension to lint *.js file?

Thanks!

### PR DESCRIPTION
**Pull request by YuichiNukiyama**
fix #51

### CODE REVIEW

**Comment by egamma** [comment]
@YuichiNukiyama thanks for the PR 💐 

@YuichiNukiyama does tslint also support linting of react `.jsx` files?

**Comment by egamma** [comment]
@YuichiNukiyama is there a configuration option in tslint.json to enable tslint in .js files? I'm testing it currently, but do not get tslint warnings in .js files

in .ts files
image

in .js files
image

**Comment by YuichiNukiyama** [comment]
@egamma Thanks for merging my PR.

> does tslint also support linting of react .jsx files?

TSLint hasn't supported .jsx files yet.

>  is there a configuration option in tslint.json to enable tslint in .js files?
>  I'm testing it currently, but do not get tslint warnings in .js files

TSLint have new options. If you want to lint js file, you shoud add **jsRules** options to tslint.json.

```
{
  "jsRules": {
    "quotemark": [true, "double", "avoid-escape"]
  },
  "rules": {
    …
  }
}
```

**Comment by egamma** [comment]
@YuichiNukiyama thanks I could now test the JS support. 

Since JS is now supported, the extension also needs to activate for `js` files.

```json
	"onLanguage:javascript",
```
I've pushed the change.

I also noticed that I don't get validation/suggestions inside the `jsRules` properties. 

`rules`
image

`jsRules`
image

The schema for `tslint.json` at `http://json.schemastore.org/tslint` should be updated to include `jsRules`.

**Comment by YuichiNukiyama** [comment]
I see. I'll try it.

**Comment by YuichiNukiyama** [comment]
done :smile:

**Comment by egamma** [comment]
excellent, thanks 🌷

**Comment by egamma** [comment]
@YuichiNukiyama regarding linting of .jsx files. It looks like this is now supported. Pls see https://github.com/palantir/tslint/pull/1714. It is an easy change to enable tslint for `javascriptreact` files, what do you think?

**Comment by YuichiNukiyama** [comment]
I think so, too. I'll send PR.

**Pull request merged**
