### PR TITLE
'AutoFixAll' accessible via keyboard shortcut + 2 new autofix rules

### PR DESCRIPTION
**Pull request by rlasjunies**
Hi this pull request  provide the capability to run the autoFixAll command via shortcut at any time (Alt+m) (#59). 

It include also 2 new rules. (#73) 

Richard

PS: Again, it's heavily inspired by the activities done on eslint.

### CODE REVIEW

**Comment by rlasjunies** [comment]
@egamma Hi Erich, Do you think that may be added in a future version?

**Comment by egamma** [comment]
@rlasjunies the PR looks good, thanks. It is high on my to do list, sorry for the delay.

**Comment by egamma** [comment]
@rlasjunies for now I haven't taken the following changes:

- changes to the .vscode files, it is not clear what the purpose of these changes is.
- the key binding definition, for eslint we have decided to defer this to the user,

**Comment by egamma** [comment]
@rlasjunies I've published the version with the PR on the marketplace.

**Comment by dcsan** [comment]
OLD issue but... is tslint now built in by default? It doesn't seem to have an auto-fix keyboard shortcut though, is there a way to add to the built-ins?

**Comment by egamma** [comment]
@dscan tslint it not built-in by default. This extension is now deprecated, pls try to the new one https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-tslint-plugin

**Comment by dcsan** [comment]
thanks! and I found the shortcut too... documented on their README

**Pull request merged**
