### PR TITLE
support of fixes provided by TSLint engine

### PR DESCRIPTION
**Pull request by rlasjunies**
Here is the proposal to support the fixes provided by TSLint engine. #84

Algo overview:
- vscode-tslint still support it's own fix  
- if fix is provided by TSLint engine, it's used  
- a part when the flag `overrideTSLintFix` of a specific rule is `true`

This proposal should support "migration" while users are not yet using latest version of tslint and exceptional case where tslint does not have all the information to apply fixes.

By the way we can apply this code now and move step by step the current vscode autoFix to TSLint engine.

@egamma, @JKillian, @alexeagle,
Let me know what do you think about it!

remark: the algo do not support the case when there are several innerReplacements. I do not see the use case and the impact on the current code seems not trivial. Can you provide examples?

@egamma,
 I've modified a little bit the wordings in the code. autoFix => vscFix or tslFix depend on the source
 I've renamed the file AutoFix.ts to vscFix.ts. And cleaned fields not used in the algo (tsLintCode, autoFixMessage, ... )

### CODE REVIEW

**Comment by egamma** [comment]
@rlasjunies I'll add this to the our October iteration plan.

**Comment by rlasjunies** [comment]
:-)

more than happy to participate!

schuzz

**Comment by egamma** [comment]
@rlasjunies I've merged in the change manually, but I acknowledged the PR in the commit message.

What is the test case you have used to verify tslint rules that come with fixes. It appears that currently only a few tslint rules have fixes?

In this commit 95fc316d74280bd2827992beec3b66dd8939adf2 I've elminated type definitions in vscode-tslint that duplicate the type defintions that come with tslint. The code is now using the types from `tslint/lib/lint`. It looks to me that the auto fix support could use more types from tslint directly rather than defining its own. 

Ideally, the vscFix.ts becomes empty soon and the fixes are contributed to tslint, then all tslint users can profit from them.

**Comment by alexeagle** [comment]
Thanks!
Yes, we still need to add fixes to many of the tslint rules.
You can use the missing/extraneous semicolon rule to manually test it (at least with tslint@next)

**Comment by rlasjunies** [comment]
Hi @egamma, @alexeagle 

 As far as I remember at the time of the implementation there were 2 autoFixes. 'semicolon', 'trailing comma'. I think I used 'semicolon'.

 About "Ideally, the vscFix.ts becomes empty". I am not sure about that. For sure the best is to have fixes coming from tsLint. But I am convinced that some use case will pop up with: "the fix depend on the configuration of the dev. env.". 
 As example, the space/tab tslint rules. autoFix should convert tab to spaces or the opposite. But how many spaces are expected for each tab found by tsLint? The number of spaces should be configured somewhere, I was feeling this should be IDE relevant. Writing this email I see this may be additional setup in tslint.json file
 
 Let see some weeks and the autoFix provided natively by tsLint.

Regards,

PS: I did not have time to move vscFixes in tsLint autofixes. I am not sure I can do in the next weeks.

**Pull request closed without merging**
